[[ORTools]]
arch = "aarch64"
git-tree-sha1 = "e28fa58547fddfba93ffd4ead386359c8f657ac1"
os = "macos"

    [[ORTools.download]]
    sha256 = "6552a147f278db6c2bb1b6f5ba860a1d22204f17f63c857aac38105c7293dff2"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.aarch64-apple-darwin.tar.gz"
[[ORTools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2301a5c39c7808267ee9869ba60a913c173ec069"
libc = "glibc"
os = "linux"

    [[ORTools.download]]
    sha256 = "264ffd2693a76b2d7b3514dc64ed91b8368cafc86c8f3d33cf5663af5c781ec6"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ORTools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "699bc5af781ed75a0e66a87beb97b2d789ac74c4"
libc = "musl"
os = "linux"

    [[ORTools.download]]
    sha256 = "5875621cdc3516d7a1768c3d9e71991740b5755d1d540b822b443f2c0aaab451"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.aarch64-linux-musl-cxx11.tar.gz"
[[ORTools]]
arch = "aarch64"
git-tree-sha1 = "c2ae5dc0df98b8f9c008c35e74b1256ab74feba8"
os = "freebsd"

    [[ORTools.download]]
    sha256 = "6d48ea7d10d718699c2ab8de60f5338cca4a3115a6025398704f7fe3b69ea2db"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.aarch64-unknown-freebsd.tar.gz"
[[ORTools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68e7c4a81fb849e69a3c72a04dced43f1c0a7939"
libc = "glibc"
os = "linux"

    [[ORTools.download]]
    sha256 = "38ea054d5bb5c58888df1c378e67b47e9af597451d80b2db08e8ec00e3e95723"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ORTools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b31c7ecf86c78363f0433eca57cfc2531ae78cf6"
libc = "musl"
os = "linux"

    [[ORTools.download]]
    sha256 = "b270f6ac86a440cc0a30ace8faf892152a187a7652d60d2215e997d2147d0ee2"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ORTools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0c40cb2eeb209364a096aaf3dc002600d312c73"
libc = "glibc"
os = "linux"

    [[ORTools.download]]
    sha256 = "8b3f62e3a09bc05c196ca25687a3400960c0795d4c679a55e7b678766b81316f"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ORTools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4a317638f98342fe13c5fd619651b59932ec5d1"
libc = "musl"
os = "linux"

    [[ORTools.download]]
    sha256 = "3a3738db1de780043e883b7348dfe2959b173be8601e0ca58dbfc772216686bc"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ORTools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa8b5fcf66857d538c96a40bfca3d0e0b039690b"
libc = "glibc"
os = "linux"

    [[ORTools.download]]
    sha256 = "76a74de38624bf5cfccf139fc955d05d3b51c0d4d19c5496d103722f540a6d4b"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.i686-linux-gnu-cxx11.tar.gz"
[[ORTools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3c9f19bfc2b2343d07b04dfdbc9745b7e5a2d09"
libc = "musl"
os = "linux"

    [[ORTools.download]]
    sha256 = "a95b6a485ba8d77ca9c9a544d28123a7f1326933355e2d76e9d2a046642fd54d"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.i686-linux-musl-cxx11.tar.gz"
[[ORTools]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6de03a0c69a2cbf2e26c59c08f4157f57f307f17"
libc = "glibc"
os = "linux"

    [[ORTools.download]]
    sha256 = "9153d88ce5b539a40e164b8e21215f77d538ab40c5842928d46351a9f0364b4b"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ORTools]]
arch = "x86_64"
git-tree-sha1 = "fef678854ae0061da5ed715357232067e5c30e74"
os = "macos"

    [[ORTools.download]]
    sha256 = "363be8974dfe0a493c77d4557bbc33c8ea1b182887ca5865517f054f3d93fa1c"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.x86_64-apple-darwin.tar.gz"
[[ORTools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d8955cfe8ba25ab792b3a8fedb6c280b6823815"
libc = "glibc"
os = "linux"

    [[ORTools.download]]
    sha256 = "2c41c16fd374df2a37dc5085e17404b7b3bfe543be4286226b89de25fd7c47e6"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ORTools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4de918e74773fffc1ccb97d7dd116c25b57e3595"
libc = "musl"
os = "linux"

    [[ORTools.download]]
    sha256 = "d68c93ca1623dce14eff1571649fa69f932efc9e79dadce20851817b1e911c2d"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.x86_64-linux-musl-cxx11.tar.gz"
[[ORTools]]
arch = "x86_64"
git-tree-sha1 = "455148d5e98ed3261f405b89b5483f0c3d5e4a46"
os = "freebsd"

    [[ORTools.download]]
    sha256 = "c99033eb08d1416e4175086405fa31e6c84353ed8030dfe4becc1b5f2ff5e84f"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.x86_64-unknown-freebsd.tar.gz"
[[ORTools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "040ab5b3ca8cb3f85f006b7d3ccb0fa02c8f4b3a"
os = "windows"

    [[ORTools.download]]
    sha256 = "64c3ac5a0f41846297f7ea92d0b40e5bc19af5ff8623ab6466f357b34bb74bf2"
    url = "https://github.com/JuliaBinaryWrappers/ORTools_jll.jl/releases/download/ORTools-v9.15.0+0/ORTools.v9.15.0.x86_64-w64-mingw32-cxx11.tar.gz"
