# Autogenerated wrapper script for ORTools_jll for x86_64-linux-gnu-cxx11
export fzncpsat, libortools, libortools_flatzinc, optional_boolean, ortools_glop_parameters, ortools_graph_flow_problem, proto_bop_parameters, proto_constraint_solver_assignment, proto_constraint_solver_demon_profiler, proto_constraint_solver_routing_enums, proto_constraint_solver_routing_parameters, proto_constraint_solver_search_limit, proto_constraint_solver_search_stats, proto_constraint_solver_solver_parameters, proto_gscip, proto_linear_solver, proto_math_opt_callback, proto_math_opt_infeasible_subsystem, proto_math_opt_model, proto_math_opt_model_parameters, proto_math_opt_model_update, proto_math_opt_parameters, proto_math_opt_result, proto_math_opt_solution, proto_math_opt_solvers_glpk, proto_math_opt_solvers_gurobi, proto_math_opt_solvers_highs, proto_math_opt_sparse_containers, proto_packing_multiple_dimensions_bin_packing, proto_packing_vector_bin_packing, proto_pdlp_solve_log, proto_pdlp_solvers, proto_sat_boolean_problem, proto_sat_cp_model, proto_sat_parameters, proto_scheduling_course_scheduling, proto_scheduling_jobshop_scheduling, proto_scheduling_rcpsp, sat_runner, solve

JLLWrappers.@generate_wrapper_header("ORTools")
JLLWrappers.@declare_library_product(libortools, "libortools.so.9")
JLLWrappers.@declare_library_product(libortools_flatzinc, "libortools_flatzinc.so.9")
JLLWrappers.@declare_executable_product(fzncpsat)
JLLWrappers.@declare_file_product(optional_boolean)
JLLWrappers.@declare_file_product(ortools_glop_parameters)
JLLWrappers.@declare_file_product(ortools_graph_flow_problem)
JLLWrappers.@declare_file_product(proto_bop_parameters)
JLLWrappers.@declare_file_product(proto_constraint_solver_assignment)
JLLWrappers.@declare_file_product(proto_constraint_solver_demon_profiler)
JLLWrappers.@declare_file_product(proto_constraint_solver_routing_enums)
JLLWrappers.@declare_file_product(proto_constraint_solver_routing_parameters)
JLLWrappers.@declare_file_product(proto_constraint_solver_search_limit)
JLLWrappers.@declare_file_product(proto_constraint_solver_search_stats)
JLLWrappers.@declare_file_product(proto_constraint_solver_solver_parameters)
JLLWrappers.@declare_file_product(proto_gscip)
JLLWrappers.@declare_file_product(proto_linear_solver)
JLLWrappers.@declare_file_product(proto_math_opt_callback)
JLLWrappers.@declare_file_product(proto_math_opt_infeasible_subsystem)
JLLWrappers.@declare_file_product(proto_math_opt_model)
JLLWrappers.@declare_file_product(proto_math_opt_model_parameters)
JLLWrappers.@declare_file_product(proto_math_opt_model_update)
JLLWrappers.@declare_file_product(proto_math_opt_parameters)
JLLWrappers.@declare_file_product(proto_math_opt_result)
JLLWrappers.@declare_file_product(proto_math_opt_solution)
JLLWrappers.@declare_file_product(proto_math_opt_solvers_glpk)
JLLWrappers.@declare_file_product(proto_math_opt_solvers_gurobi)
JLLWrappers.@declare_file_product(proto_math_opt_solvers_highs)
JLLWrappers.@declare_file_product(proto_math_opt_sparse_containers)
JLLWrappers.@declare_file_product(proto_packing_multiple_dimensions_bin_packing)
JLLWrappers.@declare_file_product(proto_packing_vector_bin_packing)
JLLWrappers.@declare_file_product(proto_pdlp_solve_log)
JLLWrappers.@declare_file_product(proto_pdlp_solvers)
JLLWrappers.@declare_file_product(proto_sat_boolean_problem)
JLLWrappers.@declare_file_product(proto_sat_cp_model)
JLLWrappers.@declare_file_product(proto_sat_parameters)
JLLWrappers.@declare_file_product(proto_scheduling_course_scheduling)
JLLWrappers.@declare_file_product(proto_scheduling_jobshop_scheduling)
JLLWrappers.@declare_file_product(proto_scheduling_rcpsp)
JLLWrappers.@declare_executable_product(sat_runner)
JLLWrappers.@declare_executable_product(solve)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libortools,
        "lib/libortools.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libortools_flatzinc,
        "lib/libortools_flatzinc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        fzncpsat,
        "bin/fzn-cp-sat",
    )

    JLLWrappers.@init_file_product(
        optional_boolean,
        "include/ortools/util/optional_boolean.proto",
    )

    JLLWrappers.@init_file_product(
        ortools_glop_parameters,
        "include/ortools/glop/parameters.proto",
    )

    JLLWrappers.@init_file_product(
        ortools_graph_flow_problem,
        "include/ortools/graph/flow_problem.proto",
    )

    JLLWrappers.@init_file_product(
        proto_bop_parameters,
        "include/ortools/bop/bop_parameters.proto",
    )

    JLLWrappers.@init_file_product(
        proto_constraint_solver_assignment,
        "include/ortools/constraint_solver/assignment.proto",
    )

    JLLWrappers.@init_file_product(
        proto_constraint_solver_demon_profiler,
        "include/ortools/constraint_solver/demon_profiler.proto",
    )

    JLLWrappers.@init_file_product(
        proto_constraint_solver_routing_enums,
        "include/ortools/constraint_solver/routing_enums.proto",
    )

    JLLWrappers.@init_file_product(
        proto_constraint_solver_routing_parameters,
        "include/ortools/constraint_solver/routing_parameters.proto",
    )

    JLLWrappers.@init_file_product(
        proto_constraint_solver_search_limit,
        "include/ortools/constraint_solver/search_limit.proto",
    )

    JLLWrappers.@init_file_product(
        proto_constraint_solver_search_stats,
        "include/ortools/constraint_solver/search_stats.proto",
    )

    JLLWrappers.@init_file_product(
        proto_constraint_solver_solver_parameters,
        "include/ortools/constraint_solver/solver_parameters.proto",
    )

    JLLWrappers.@init_file_product(
        proto_gscip,
        "include/ortools/gscip/gscip.proto",
    )

    JLLWrappers.@init_file_product(
        proto_linear_solver,
        "include/ortools/linear_solver/linear_solver.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_callback,
        "include/ortools/math_opt/callback.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_infeasible_subsystem,
        "include/ortools/math_opt/infeasible_subsystem.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_model,
        "include/ortools/math_opt/model.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_model_parameters,
        "include/ortools/math_opt/model_parameters.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_model_update,
        "include/ortools/math_opt/model_update.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_parameters,
        "include/ortools/math_opt/parameters.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_result,
        "include/ortools/math_opt/result.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_solution,
        "include/ortools/math_opt/solution.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_solvers_glpk,
        "include/ortools/math_opt/solvers/glpk.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_solvers_gurobi,
        "include/ortools/math_opt/solvers/gurobi.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_solvers_highs,
        "include/ortools/math_opt/solvers/highs.proto",
    )

    JLLWrappers.@init_file_product(
        proto_math_opt_sparse_containers,
        "include/ortools/math_opt/sparse_containers.proto",
    )

    JLLWrappers.@init_file_product(
        proto_packing_multiple_dimensions_bin_packing,
        "include/ortools/packing/multiple_dimensions_bin_packing.proto",
    )

    JLLWrappers.@init_file_product(
        proto_packing_vector_bin_packing,
        "include/ortools/packing/vbp/vector_bin_packing.proto",
    )

    JLLWrappers.@init_file_product(
        proto_pdlp_solve_log,
        "include/ortools/pdlp/solve_log.proto",
    )

    JLLWrappers.@init_file_product(
        proto_pdlp_solvers,
        "include/ortools/pdlp/solvers.proto",
    )

    JLLWrappers.@init_file_product(
        proto_sat_boolean_problem,
        "include/ortools/sat/boolean_problem.proto",
    )

    JLLWrappers.@init_file_product(
        proto_sat_cp_model,
        "include/ortools/sat/cp_model.proto",
    )

    JLLWrappers.@init_file_product(
        proto_sat_parameters,
        "include/ortools/sat/sat_parameters.proto",
    )

    JLLWrappers.@init_file_product(
        proto_scheduling_course_scheduling,
        "include/ortools/scheduling/course_scheduling.proto",
    )

    JLLWrappers.@init_file_product(
        proto_scheduling_jobshop_scheduling,
        "include/ortools/scheduling/jssp/jobshop_scheduling.proto",
    )

    JLLWrappers.@init_file_product(
        proto_scheduling_rcpsp,
        "include/ortools/scheduling/rcpsp/rcpsp.proto",
    )

    JLLWrappers.@init_executable_product(
        sat_runner,
        "bin/sat_runner",
    )

    JLLWrappers.@init_executable_product(
        solve,
        "bin/solve",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
